spring:
  datasource:
    url: jdbc:db2://b0aebb68-94fa-46ec-a1fc-1c999edb6187.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud:31249/bludb:sslConnection=true;
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    username: ldc62889
    password: ltpBdOZs6OIiG4kP
  hikari:
    minimum-idle: 3
    maximum-pool-size: 5
    idle-timeout: 30000 # in milliseconds (30 seconds)
    connectionTimeout: 30000
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect